Repository momentPics/moment_client, pull requests merged in 2023-10, with the labels that each got.

#34 feat: 앨범 상세 페이지 추가
  frontend/package.json
  frontend/src/assets/icons/BackIcon.tsx
  frontend/src/assets/icons/DeleteDetailIcon.tsx
  frontend/src/assets/icons/MessageDetailIcon.tsx
  frontend/src/assets/icons/MoreIcon.tsx
  frontend/src/components/albumDetail/AlbumDetail.styled.ts
  frontend/src/components/albumDetail/AlbumDetailFooter.tsx
  frontend/src/components/albumDetail/AlbumDetailImage.tsx
  frontend/src/components/albumDetail/swiperCustom.css
  frontend/src/components/home/HomeAlbum.styled.ts
  frontend/src/components/home/HomeAlbum.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/AlbumDetail/index.tsx
  frontend/src/router/index.tsx
  frontend/src/stores/albumDetailStore.ts
  frontend/src/types/album.ts
  frontend/src/utils/formatDate.ts
  frontend/src/utils/validate.ts
  frontend/yarn.lock
Labels: ⚙ Setting, 🔨 Refactor, 🎨 HTML&CSS, ✨ Feature, FE

#35 feat: access token 관련 작업 및 권한 분기
  frontend/index.html
  frontend/src/api/auth/index.ts
  frontend/src/api/axios.ts
  frontend/src/hoc/withAuth.tsx
  frontend/src/hooks/useGetAccessToken.ts
  frontend/src/pages/Test/index.tsx
  frontend/src/router/Redirection.tsx
  frontend/src/stores/accessToken.ts
  frontend/src/types/user.ts
  frontend/yarn.lock
Labels: ⚙ Setting, ✨ Feature, FE

#37 refactor: Router 구조 및 withAuth HOC 수정
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/hoc/withAuth.tsx
  src/pages/AuthRedirection/index.tsx
  src/provider/LayoutProvider.tsx
  src/router/PrivateProvider.tsx
  src/router/PublicProvider.tsx
  src/router/index.tsx
  yarn.lock
Labels: 🔨 Refactor, 🐞 Bug Fix, FE

#42 refactor: 모달 내 불필요한 코드 제거 및 ESLint 일부 및 중복 제거
  .eslintignore
  .eslintrc.cjs
  index.html
  src/components/albumDetail/AlbumDetailFooter.tsx
  src/components/common/Modal/DeletePhotoModal.tsx
  src/components/common/Modal/MessageMenuModal.tsx
  src/components/layout/Header/index.tsx
  src/components/login/SocialButton.tsx
  src/hoc/withAuth.tsx
  src/hooks/useGetAccessToken.ts
  src/hooks/useVisible.ts
  src/main.tsx
  src/pages/AuthRedirection/index.tsx
  src/pages/Home/index.tsx
  src/pages/Test/index.tsx
  src/utils/formatDate.ts
Labels: 🔨 Refactor, 🐞 Bug Fix, FE

#43 feat: 앨범 상세 페이지 내 메세지 영역 추가 및 모달 리팩토링
  .eslintrc.cjs
  package.json
  src/App.tsx
  src/api/album/index.ts
  src/assets/icons/MessageDetailIcon.tsx
  src/components/albumDetail/AlbumDetail.styled.ts
  src/components/albumDetail/AlbumDetailFooter.tsx
  src/components/albumDetail/AlbumDetailImage.tsx
  src/components/common/Modal/DeleteConfirmModal.tsx
  src/components/common/Modal/DeletePhotoModal.tsx
  src/components/common/Modal/MessageMenuModal.tsx
  src/components/common/Modal/Modal.styled.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/MoreModal.tsx
  src/components/home/HomeAlbum.tsx
  src/components/layout/Header/index.tsx
  src/hooks/useHandleDeleteBoardData.ts
  src/hooks/usePreventScroll.ts
  src/hooks/useVisible.ts
  src/main.tsx
  src/mocks/index.ts
  src/pages/Test/index.tsx
  src/provider/ModalProvider.tsx
  src/stores/activeSliderStore.ts
  src/stores/messageStore.ts
  src/types/album.ts
  src/utils/formatDate.ts
  src/utils/index.ts
  yarn.lock
Labels: 🔨 Refactor, 🎨 HTML&CSS, ✨ Feature, FE

#45 refactor: host_03 페이지 전체적으로 리팩토링
  src/components/albumDetail/AlbumDetailFooter.tsx
  src/components/albumDetail/AlbumDetailImage.tsx
  src/pages/Home/index.tsx
Labels: 🔨 Refactor, FE

#48 refactor: 콘텐츠 없는 페이지 수정
  src/components/albumDetail/AlbumDetailImage.tsx
  src/components/home/HomeAlbum.tsx
  src/components/layout/NoneContent/NoneContent.styled.ts
  src/components/layout/NoneContent/index.tsx
  src/hooks/useHandleDeleteBoardData.ts
  src/hooks/useInfinityObserver.ts
  src/pages/Home/index.tsx
  src/types/album.ts
Labels: 🔨 Refactor, FE

#50 refactor: 삭제 관련 비즈니스 플로우 변경으로 인한 디자인 변경점 적용
  src/components/albumDetail/AlbumDetailFooter.tsx
  src/components/common/Modal/DeleteConfirmModal.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/MoreModal.tsx
  src/components/layout/Header/index.tsx
  src/hooks/useHandleDeleteBoardData.ts
  src/provider/ModalProvider.tsx
Labels: 🔨 Refactor, FE

#53 refactor:host 04 스타일링 수정
  src/assets/icons/MessageRightIcon.tsx
  src/components/messages/Message.styled.tsx
  src/components/messages/MessagesList.tsx
Labels: 🔨 Refactor, FE

#54 feat: JWT 토큰 활용에 따른 전체적인 코드 수정
  package.json
  src/App.tsx
  src/api/album/index.ts
  src/api/auth/index.ts
  src/api/messages/index.tsx
  src/assets/icons/MessageRightIcon.tsx
  src/assets/icons/RightIcon.tsx
  src/components/albumDetail/AlbumDetailFooter.tsx
  src/components/albumDetail/AlbumDetailImage.tsx
  src/components/layout/Header/index.tsx
  src/components/messages/MessagesList.tsx
  src/hoc/withAuth.tsx
  src/hooks/useGetAccessToken.ts
  src/hooks/useHandleDeleteBoardData.ts
  src/main.tsx
  src/pages/AuthRedirection/index.tsx
  src/provider/LayoutProvider.tsx
  src/stores/accessToken.ts
  src/stores/userStore.ts
  src/types/user.ts
  yarn.lock
Labels: 🔨 Refactor, FE

#55 feat:detail 페이지 최소기능 구현
  src/api/messages/index.tsx
  src/components/messages/MessageDetail.tsx
  src/components/messages/MessageSwiper.css
  src/components/messages/Messagedetail.styled.tsx
  src/components/messages/MessagesList.tsx
  src/constants/routes.ts
  src/hooks/useMessageDetail.ts
  src/hooks/useMessageList.ts
  src/pages/MessageDetail/index.tsx
  src/types/message.ts
Labels: ✨ Feature, FE

#58 feat: 마이 페이지 전체 레이아웃 추가
  src/api/axios.ts
  src/api/mypage/index.ts
  src/components/common/Skeleton/ProfileCount.tsx
  src/components/common/Skeleton/index.ts
  src/components/layout/Header/index.tsx
  src/components/mypage/CountCount.tsx
  src/components/mypage/Profile.styled.ts
  src/components/mypage/Profile.tsx
  src/components/mypage/UserMenu.tsx
  src/constants/routes.ts
  src/constants/styles.ts
  src/pages/MyPage/index.tsx
  src/provider/LayoutProvider.tsx
  src/router/index.tsx
Labels: 🎨 HTML&CSS, ✨ Feature, FE
