Repository momentPics/moment_client, pull requests merged in 2023-09, with the labels that each got.

#6 setting: 개발 환경, 반응형, 라우터 설정
  frontend/.prettierrc.cjs
  frontend/index.html
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/router/index.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/yarn.lock
Labels: ⚙ Setting, FE

#7 test: 모바일 환경 테스트
  frontend/src/pages/Home/index.tsx
Labels: ✅ Test, FE

#8 setting: react-query 설정, 반응형 세팅
  frontend/package.json
  frontend/src/components/layout/Header/index.tsx
  frontend/src/constants/mediaQuery.ts
  frontend/src/constants/screenBreakpoints.ts
  frontend/src/hooks/useMediaQuery.ts
  frontend/src/main.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/yarn.lock
Labels: ⚙ Setting, 🎨 HTML&CSS, FE

#9 fix(deploy): Github Action 내 캐싱 관련 추가, 반응형 관련 유니온 타입 제거
  .github/workflows/frontend-deploy-work.yml
  frontend/src/components/layout/Header/index.tsx
  frontend/src/constants/screenBreakpoints.ts
  frontend/src/constants/styles.ts
  frontend/src/hooks/useMediaQuery.ts
  frontend/src/pages/Home/index.tsx
Labels: ✅ Test, 🔨 Refactor, 🐞 Bug Fix, FE

#10 remove: .DS_Store 파일 삭제
  .DS_Store
Labels: ⚙ Setting

#13 style: 헤더, 푸터 추가 및 기본 레이아웃 설정
  frontend/src/App.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/constants/styles.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/styles/GlobalStyles.ts
Labels: 🎨 HTML&CSS, FE

#14 feat: 파비콘 및 private, public 라우터 추가
  frontend/index.html
  frontend/public/icons/favicon-16x16.png
  frontend/public/icons/favicon-32x32.png
  frontend/public/icons/favicon-96x96.png
  frontend/public/icons/favicon.ico
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/router/PrivateProvider.tsx
  frontend/src/router/PublicProvider.tsx
  frontend/src/router/index.tsx
Labels: ⚙ Setting, 🔨 Refactor, ✨ Feature, FE

#15 feat: 로그인 페이지 추가 및 host_01 레이아웃 완료
  frontend/src/assets/kakao_login.png
  frontend/src/assets/moment.svg
  frontend/src/assets/react.svg
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/components/login/Logo.tsx
  frontend/src/components/login/SocialButton.tsx
  frontend/src/pages/Login/index.tsx
Labels: 🎨 HTML&CSS, 🖐 Enhancement, FE

#17 style: 전체적인 스타일 변경
  frontend/src/App.tsx
  frontend/src/assets/fonts/NexonGothicBold.woff
  frontend/src/assets/fonts/NexonGothicLight.woff
  frontend/src/assets/fonts/NexonGothicMedium.woff
  frontend/src/assets/kakao_login.png
  frontend/src/assets/kakao_login.svg
  frontend/src/components/Button.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/components/login/SocialButton.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/router/PublicProvider.tsx
  frontend/src/styles/GlobalStyles.ts
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/styles.ts
Labels: 🎨 HTML&CSS, FE

#20 feat: 카카오 로그인 연동 및 MSW 수정
  frontend/.env
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/login/SocialButton.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/router/Redirection.tsx
  frontend/src/router/index.tsx
Labels: ✨ Feature, FE

#22 test(deploy): GitHub Actions 테스트
  .github/workflows/frontend-deploy-work.yml
  frontend/src/pages/Home/index.tsx
Labels: 🌏 Infra, FE

#24 [FE] 헤더, 푸터 디자인 적용 및 타이포그래피 DefaultTheme 설정
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/assets/album.svg
  frontend/src/assets/back.svg
  frontend/src/assets/message.svg
  frontend/src/assets/more.svg
  frontend/src/assets/my.svg
  frontend/src/components/layout/Footer/Footer.stories.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/Header.stories.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/constants/styles.ts
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Configure.mdx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/accessibility.png
  frontend/src/stories/assets/accessibility.svg
  frontend/src/stories/assets/addon-library.png
  frontend/src/stories/assets/assets.png
  frontend/src/stories/assets/context.png
  frontend/src/stories/assets/discord.svg
  frontend/src/stories/assets/docs.png
  frontend/src/stories/assets/figma-plugin.png
  frontend/src/stories/assets/github.svg
  frontend/src/stories/assets/share.png
  frontend/src/stories/assets/styling.png
  frontend/src/stories/assets/testing.png
  frontend/src/stories/assets/theming.png
  frontend/src/stories/assets/tutorials.svg
  frontend/src/stories/assets/youtube.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
  frontend/yarn.lock
Labels: 🎨 Storybook, 🎨 HTML&CSS, FE

#23 feat: 카카오 로그인 커스텀 훅 및 Github action 환경변수 추가
  .github/workflows/frontend-deploy-work.yml
  frontend/.env
  frontend/.gitignore
  frontend/src/App.tsx
  frontend/src/hooks/useKakaoLogin.ts
  frontend/src/main.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/router/Redirection.tsx
Labels: ⚙ Setting, ✨ Feature, FE

#27 refactor: Header 및 최초 진입 메인 페이지 수정
  frontend/package.json
  frontend/src/api/auth/index.ts
  frontend/src/api/axios.ts
  frontend/src/assets/right.svg
  frontend/src/components/home/HomeAlbum.styled.ts
  frontend/src/components/home/HomeAlbum.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/NoneContent/NoneContent.styled.ts
  frontend/src/components/layout/NoneContent/index.tsx
  frontend/src/constants/api.ts
  frontend/src/constants/routes.ts
  frontend/src/main.tsx
  frontend/src/mocks/data/services.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/router/Redirection.tsx
  frontend/src/router/index.tsx
  frontend/src/stores/userStore.ts
  frontend/src/types/user.ts
  frontend/src/utils/fetchQuery.ts
  frontend/yarn.lock
Labels: 🔨 Refactor, 🎨 HTML&CSS, ✨ Feature, FE

#30 refactor: Footer 하단 아이콘 경로에 따른 활성화 및 SVG 컴포넌트화
  frontend/package.json
  frontend/src/api/axios.ts
  frontend/src/assets/album.svg
  frontend/src/assets/back.svg
  frontend/src/assets/delete.svg
  frontend/src/assets/icons/AlbumIcon.tsx
  frontend/src/assets/icons/BackIcon.tsx
  frontend/src/assets/icons/DeleteIcon.tsx
  frontend/src/assets/icons/MessageIcon.tsx
  frontend/src/assets/icons/MoreIcon.tsx
  frontend/src/assets/icons/MyPageIcon.tsx
  frontend/src/assets/icons/RightIcon.tsx
  frontend/src/assets/images/kakao_login.png
  frontend/src/assets/images/moment.png
  frontend/src/assets/kakao_login.svg
  frontend/src/assets/message.svg
  frontend/src/assets/moment.svg
  frontend/src/assets/more.svg
  frontend/src/assets/my.svg
  frontend/src/assets/right.svg
  frontend/src/components/common/modal/MessageMenuModal.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/login/Logo.tsx
  frontend/src/components/login/SocialButton.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/styles.ts
  frontend/src/router/index.tsx
  frontend/src/types/user.ts
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 🔨 Refactor, 🎨 HTML&CSS, FE

#32 feat: 메인 앨범 무한스크롤 및 Lazy Loading, 스켈레톤 ui 추가, 일부 코드 수정 및 리팩토링
  frontend/.storybook/main.ts
  frontend/public/mockServiceWorker.js
  frontend/public/vite.svg
  frontend/src/api/album/index.ts
  frontend/src/components/common/LazyImage/index.tsx
  frontend/src/components/common/Skeleton/Image.tsx
  frontend/src/components/common/Skeleton/index.ts
  frontend/src/components/home/HomeAlbum.styled.ts
  frontend/src/components/home/HomeAlbum.tsx
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/hooks/useInfinityAlbum.ts
  frontend/src/hooks/useInfinityObserver.ts
  frontend/src/hooks/useLazyImageObserver.ts
  frontend/src/pages/Home/index.tsx
  frontend/src/router/Redirection.tsx
  frontend/src/stores/userStore.ts
  frontend/src/types/album.ts
  frontend/yarn.lock
Labels: 🎨 Storybook, 🔨 Refactor, 🎨 HTML&CSS, ✨ Feature, FE

#33 style: 디자인 고도화에 따른 스타일 및 아이콘 변경
  frontend/src/assets/icons/BackIcon.tsx
  frontend/src/assets/icons/MoreIcon.tsx
  frontend/src/assets/icons/RightIcon.tsx
  frontend/src/components/common/LazyImage/index.tsx
  frontend/src/components/common/Skeleton/AlbumImage.tsx
  frontend/src/components/common/Skeleton/index.ts
  frontend/src/components/home/HomeAlbum.styled.ts
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/MomentBody/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/styles/styled.d.ts
  frontend/src/styles/theme.ts
Labels: 🎨 HTML&CSS, ✨ Feature, FE
